sudo: false
language: node_js
node_js:
- '4'

env:
  global:
    - SAUCE_USERNAME=opbeat
    - SAUCE_ACCESS_KEY=de42e589-1450-41a2-8a44-90aa00c15168
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    # - MODE=saucelabs_optional
    - MODE=saucelabs ANGULAR_VERSION="~1.2.0"
    - MODE=saucelabs ANGULAR_VERSION="~1.3.0"
    - MODE=saucelabs ANGULAR_VERSION="~1.4.0"
    - MODE=saucelabs ANGULAR_VERSION="~1.5.0"

matrix:
  allow_failures:
    - env: "MODE=saucelabs_optional"   

cache:
  directories:
  - node_modules
  - test/e2e/node_modules

addons:
 firefox: "38.0"

before_script:
  - (cd test/e2e && npm install && npm install angular@$ANGULAR_VERSION angular-resource@$ANGULAR_VERSION angular-route@$ANGULAR_VERSION)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

notifications:
  slack:
    secure: bvZ3eA7e4svhe/ak5Hbv45Ghpevi4rDxyNIIvZ8IS4QUhJ2YcJfp8EC9yrBwdWInVtqrOWHwPspLScMI2go6xLYJJ5wUtNwaxLTzF7XmRA7j94kIGNLGAMcxkAtWRFfctE5gjRBdYs4j/ISy+cGC0a5wcBwOZY2U743e+b2aYe8YlFGxHlDtxoiuTqGv8HJiSbHPmRSxd+3QFjLxIIHUwZRSOHwjIPMzaKFMWyyHxijXsZbcvYQ25ZqejmfcR6OIwdfJ9ostL0lmA6sblsLjNYWcjmgeNMHtBws1txSGDPb0MjvaSHF0iRCWyQs9UOoEiKqyS/6z6EJJ2mO1b3tGJhJFrZeyqafdFeTPIbRSNsk0EEZnvq+cX7yGEr6cHVZ4r/IxpcEzsGD/lkubasEoTwD81G/BjszNFc2h3HXAHawLibmu6ZvPSuQfUyGy3Clv/lTDzrQgRaDg8poreSEQZaTVjqOPyMolll/NboWhaTX+CMJxAYZ3UT3kXUrfDR0QNF/XRU82c9t3UYF2H8R8Z0yg5Eu+7MRi3o2Gl81ZhLVtVQp5w9lPZxXtZOoZHTskWbNo3AMVcbN40SmTUSiYkoaQ7W0S5puBvHirwHqti3AOtjDfDVIp3aGR3lZoJDsraCiHbPHWUaTnfuASVOTUEB2NFDp4xGF9ie86Tom8H7Q=
