sudo: false
language: node_js
node_js:
- '4'

env:
  global:
    - SAUCE_USERNAME=opbeat
    - SAUCE_ACCESS_KEY=de42e589-1450-41a2-8a44-90aa00c15168
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    # - MODE=saucelabs_optional
    - MODE=saucelabs ANGULAR_VERSION="~1.2.0"
    - MODE=saucelabs ANGULAR_VERSION="~1.3.0"
    - MODE=saucelabs ANGULAR_VERSION="~1.4.0"
    - MODE=saucelabs ANGULAR_VERSION="~1.5.0"

matrix:
  allow_failures:
    - env: "MODE=saucelabs_optional"   

cache:
  directories:
  - node_modules
  - test/e2e/node_modules

addons:
 firefox: "38.0"

before_script:
  - (cd test/e2e && npm install && npm install angular@$ANGULAR_VERSION angular-animate@$ANGULAR_VERSION angular-resource@$ANGULAR_VERSION angular-route@$ANGULAR_VERSION)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start